### ISSUE TITLE
soft link to the mount errors

### ISSUE THREAD

**Issue by metsuke0** [joyent/manta-nfs#25]
OS: Centos 6.8 on top of kvm in the Joyent Cloud

mount method: mount -o nolock 127.0.0.1:/[username]/stor /mnt

I can interact with files and directories in the manta-nfs mount, but when I use 'ln -s /mnt /other_dir' and then try to interact with the link, I get an error: 

ls: reading directory /other_dir/: Input/output error

Are soft links to the manta-nfs mounts possible or is there just possibly something wrong with the system config?

**Comment by jjelinek** [comment]
Because manta itself does not support either soft or hard links, that is unsupported. This is noted in the "Limitations" section of the Readme.

**Comment by metsuke0** [comment]
Ok, thanks.  I didn't know if the limitation extended to a link outside of the mount to the root, but that makes sense as well.
